### ISSUE TITLE
Runtime Error when trying to run project with hooligan theme

### ISSUE THREAD

**Issue by cyberjar09** [ruhoh/hooligan#7]
I am running ruhoh 2.5 RuhohSpec 2.1 on my Ubuntu 13.10 box, ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]

I cloned the hooligan theme into my project root and created a config.yml file with the text 
theme: "hooligan"

I get the following stack trace when I try to start my server 

`rudy@rudy-bangalore-pc:/var/www/blog$ bundle exec ruhoh server 9292
/home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/parse.rb:28:in `rescue in page_file': Error trying to read meta-data from /var/www/blog/hooligan/media/bgs/body.png. Check your folder configuration.  Error details: invalid byte sequence in UTF-8 (RuntimeError)
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/parse.rb:19:in `page_file'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/base/model.rb:104:in `parse_page_file'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/base/model.rb:60:in `process'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/base/model.rb:18:in `data'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/base/model_view.rb:12:in `initialize'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/base/collection.rb:207:in `new'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/base/collection.rb:207:in `load_model_view'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/base/collection.rb:30:in `find'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/base/collection.rb:39:in `block in dictionary'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/base/collection.rb:37:in `each'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/base/collection.rb:37:in `dictionary'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/resources/pages/collection.rb:6:in `routes'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/routes.rb:24:in `block in all'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/routes.rb:23:in `each'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/routes.rb:23:in `all'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/programs/preview.rb:26:in `preview'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/client.rb:122:in `server'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/lib/ruhoh/client.rb:40:in `initialize'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/bin/ruhoh:34:in `new'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.5/bin/ruhoh:34:in `<top (required)>'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/bin/ruhoh:23:in `load'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/bin/ruhoh:23:in `<main>'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
    from /home/rudy/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'`

The problem seems to be originating from `/var/www/blog/hooligan/media/bgs/body.png` where `/var/www/blog` is my project root. 

I have changed the permissions of my project root already 
`chown -R rudy:rudy /var/www/blog`

Not sure how to proceed never worked with ruby ever before.

**Comment by plusjade** [comment]
The config format is incorrect, it needs to be:

"theme" :
  "use" : "hooligan"

Please try that, restart the web-server, and let me know if it works!

**Comment by Jiraiyah** [comment]
I tried the setting in the ream me, gave me the same error, then i tried this new setting, still same error and the server won't start. please help
